from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class AiAuditRecord(BaseModel):
    """Matches `packages/db` model `AiRequestLog` (persisted by API / optional Python hook).

    JSON Schema contract for cross-language tooling: `schemas/json/ai-audit.record.json`
    (generated by `python app/scripts/export_schemas.py`).
    """

    endpoint: str
    model: str
    promptTokens: int = Field(ge=0)
    completionTokens: int = Field(ge=0)
    totalTokens: int = Field(ge=0)
    costUsd: float = Field(ge=0)
    durationMs: int = Field(ge=0)
    status: str  # success, error, rate_limited
    errorMessage: str | None = None
    requestPayload: dict[str, Any] | None = None
    responsePayload: dict[str, Any] | None = None


class AuditSummary(BaseModel):
    """Subset returned to callers (no DB id until API persists)."""

    model: str
    promptTokens: int
    completionTokens: int
    totalTokens: int
    costUsd: float
    durationMs: int
    status: str
